### ISSUE TITLE
Amazing job!

### ISSUE THREAD

**Issue by TwinProduction** [avakarev/gatus-chart#17]
Hey @avakarev, this isn't really an issue, but as I was about to create a helm chart in [my repository of helm charts](https://github.com/TwinProduction/helm-charts) for Gatus, I noticed your work.

I just wanted you to know that you've done awesome work, and if you'd like to create a PR on [TwinProduction/gatus](https://github.com/TwinProduction/gatus) to add a link to this repository in the documentation (along with a new section titled "Helm" or something similar), I would gladly merge it!

In any case, thanks again :)

(Feel free to close this as you see fit)

**Comment by avakarev** [comment]
Hi @TwinProduction, I glad that you found this helm chart useful. Thank you for your great work on Gatus! Sure, I can create a PR for Gatus repo to add a link. Will do it today or tomorrow.
