### ISSUE TITLE
Release missing

### ISSUE THREAD

**Issue by mdraijer** [avakarev/gatus-chart#20]
Your commits show that you have released 1.1.3, however there is no Release with that name.

**Comment by mrchypark** [comment]
maybe only use tag without release.

helm chart index has 1.1.3 version. So works fine.

**Comment by avakarev** [comment]
Yeah, versions represented by tags for now. But it makes sense to start using gitub releases with documented changes cause new version with breaking config changes (due to new storage options at gatus config) is on its way.
