### ISSUE TITLE
Changing configmap values triggers pod restart

### ISSUE THREAD

**Issue by martinlillemets** [avakarev/gatus-chart#49]
It seems that the chart contains invalid configuration in deployment.yaml which restarts gatus pod every time there is a change in configmap.

Because gatus supports hot-reload of configuration file, changing configmap should not trigger pod restart.

Steps to reproduce
```
1. Deploy the chart
2. Modify any of the endpoints values
3. Run helm upgrade
4. Pod restarted
```

The culprit is the following line: `gatus/templates/deployment.yaml:30`
`checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}`
I believe this line is unneeded for this application due to hot-reloading capabilities of the underlying application and could be removed safely.

If this can be confirmed as a bug I am willing to create a Pull request with the relevant fix

Relevant version information:
gatus version
```
chart version: gatus-2.5.5
app version: v4.3.2
```
helm version
```
{
  Version: "v3.9.0",
  GitCommit: "7ceeda6c585217a19a1131663d8cd1f7d641b2a7",
  GitTreeState: "clean",
  GoVersion: "go1.17.5"
}

```

**Comment by avakarev** [comment]
Hi @martinlillemets, thank you for the issue. I see your point, gatus can re-read the config "on-the-fly" with some delay (about 30s). Personally I prefer to annotate pod, so gatus is restarted on each config change and there is an immediate "feedback" if config is not valid. 

I've added a flag to disable the config checksum: set `deployment.annotateConfigChecksum` to `false`. See https://github.com/avakarev/gatus-chart/pull/50/files for details, version `2.6.0` is released.

I'm closing the issue. Please, let me know if you still have problem with config reload.
